config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                      Controller#Action
#                     root GET    /                                landing#index
#         new_user_session GET    /users/sign_in(.:format)         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
# cancel_user_registration GET    /users/cancel(.:format)          devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)            devise/registrations#edit
#        user_registration PATCH  /users(.:format)                 devise/registrations#update
#                          PUT    /users(.:format)                 devise/registrations#update
#                          DELETE /users(.:format)                 devise/registrations#destroy
#                          POST   /users(.:format)                 devise/registrations#create
#             admin_offers GET    /admin/offers(.:format)          admin/offers#index
#                          POST   /admin/offers(.:format)          admin/offers#create
#          new_admin_offer GET    /admin/offers/new(.:format)      admin/offers#new
#         edit_admin_offer GET    /admin/offers/:id/edit(.:format) admin/offers#edit
#              admin_offer GET    /admin/offers/:id(.:format)      admin/offers#show
#                          PATCH  /admin/offers/:id(.:format)      admin/offers#update
#                          PUT    /admin/offers/:id(.:format)      admin/offers#update
#                          DELETE /admin/offers/:id(.:format)      admin/offers#destroy
#

Rails.application.routes.draw do
  root 'landing#index'

  devise_for :users

  namespace :admin do
    root 'offers#index'
    resources :offers do
      get 'enable', on: :member
      get 'disable', on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id              :integer          not null, primary key
#  advertiser_name :string
#  url             :string
#  description     :text
#  starts_at       :datetime
#  ends_at         :datetime
#  offer_type      :integer          default("regular"), not null
#  status          :integer          default("disabled"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_offers_on_advertiser_name  (advertiser_name) UNIQUE
#

class Offer < ApplicationRecord
  enum offer_type:[:regular, :premium]
  enum status:[:disabled, :enabled]

  #TODO move validations to Reform form object
  validates_presence_of :advertiser_name
  validates_uniqueness_of :advertiser_name
  validates :description, presence: true, length: { maximum: 500 }
  validates :url, presence: true, :format => URI::regexp(%w(http https))
  validates_presence_of :starts_at

  scope :active, -> { where(status:Offer.statuses[:enabled]).where("starts_at <= ?", Time.now).where("ends_at >= ? OR ends_at IS NULL", Time.now)}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string           default(""), not null
#  encrypted_password  :string           default(""), not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :inet
#  last_sign_in_ip     :inet
#  role                :integer          default("customer"), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable,
  # :recoverable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  enum role:[:customer, :admin]

end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    layout 'admin'
    include Pundit
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :authorize_admin!

    private
    def authorize_admin!
      #very basic don't need yet to use Pundit
      if !current_user.admin?
        return redirect_to '/', notice: "You don't have permissions"
      end
    end
  end
end

app/controllers/admin/offers_controller.rb
module Admin
  class OffersController < Admin::ApplicationController
    before_action :set_offer, only: [:show, :edit, :update, :destroy, :enable, :disable]
    respond_to :html
    # GET /offers
    def index
      @offers = ::OfferDecorator.decorate_collection(Offer.all)
    end

    # GET /offers/1
    def show
    end

    # GET /offers/new
    def new
      @offer = Offer.new
    end

    # GET /offers/1/edit
    def edit
    end

    # POST /offers
    def create
      @offer = Offer.new(offer_params)
      if @offer.save
        redirect_to admin_offers_url, notice: 'Offer was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /offers/1
    # PATCH/PUT /offers/1.json
    def update
      if @offer.update(offer_params)
        redirect_to admin_offers_url, notice: 'Offer was successfully updated.'
      else
        render :edit
      end
    end

    #Don't like toggle because of consistency problems
    def enable
      if @offer.enabled!
        redirect_to admin_offers_url, notice: 'Offer was successfully enabled.'
      else
        redirect_to admin_offers_url, error: "Couldn't handle the request." #just in case - unreachable code
      end
    end

    def disable
      if @offer.disabled!
        redirect_to admin_offers_url, notice: 'Offer was successfully disabled.'
      else
        redirect_to admin_offers_url, error: "Couldn't handle the request." #just in case - unreachable code
      end

    end

    # DELETE /offers/1
    # DELETE /offers/1.json
    def destroy
      @offer.destroy
      redirect_to admin_offers_url, notice: 'Offer was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_offer
        @offer = Offer.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def offer_params
        params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :offer_type)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @offers = Offer.active.order(offer_type: 'desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/offers/_form.slim
= simple_form_for([:admin, @offer]) do |f|
  = f.error_notification
  .form-inputs
    = f.input :advertiser_name
    = f.input :url
    = f.input :description
    = f.input :starts_at
    = f.input :ends_at
    = f.input :offer_type, as: :boolean, label:'Premium:_' do
      = f.check_box :offer_type, {}, "premium", "regular"
  .form-actions.btn-toolbar.justify-content-between
    = f.button :submit
    = link_to 'Cancel', admin_offers_path, class: "btn btn-danger"

app/views/admin/offers/edit.slim
h1 Editing Offer
= render 'form', offer: @offer

app/views/admin/offers/index.slim
.row
  p#notice= notice
  h1 Offers
  .table-responsive
    table.table.table-striped
      thead
        tr
          th Advertiser name
          th Url
          th Description
          th Starts at
          th Ends at
          th Offer Type
          th colspan="3"
      tbody
        - @offers.each do |offer|
          tr
            td= offer.advertiser_name
            td= offer.url
            td= offer.description
            td= offer.starts_at
            td= offer.ends_at
            td= offer.offer_type
            td= offer.togle_status_link
            td= link_to 'Edit', edit_admin_offer_path(offer)
            td= link_to 'Destroy', [:admin,offer], method: :delete, data:{confirm: 'Are you sure?'}
  br/
  = link_to 'New Offer', new_admin_offer_path, class: 'btn btn-primary'

app/views/admin/offers/new.slim
h1 New Offer
= render 'form', offer: @offer

app/views/admin/offers/show.slim
p#notice= notice
p
  strong Advertiser name:
  = @offer.advertiser_name
p
  strong Url:
  = @offer.url
p
  strong Description:
  = @offer.description
p
  strong Starts at:
  = @offer.starts_at
p
  strong Ends at:
  = @offer.ends_at
p
  strong Offer Type:
  = @offer.offer_type
= link_to 'Edit', edit_admin_offer_path(@offer)
| \
= link_to 'Back', admin_offers_path

app/views/landing/_offer.slim
.col-md-6.col-sm-12
  .offer-box class="#{'premium' if offer.premium? }"
    span.badge.badge-danger.badge-pill premium
    .offer-title
      h2= offer.advertiser_name
    .offer-action
      = link_to "Shop Now", offer.url, class:"btn"

app/views/landing/index.slim
.row.justify-content-around
  -@offers.all.each do |offer|
   = render partial: 'offer', locals: {offer: offer}

app/views/layouts/admin.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta name="robots" content="noindex,nofollow" /
    title LemoneyChallenge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-inverse.bg-primary.navbar-toggleable-md
      button.navbar-toggler.navbar-toggler-right aria-controls="adminNavbar" aria-expanded="false" aria-label=("Toggle navigation") data-target="#adminNavbar" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      a.navbar-brand href='/' Challenge
      #adminNavbar.collapse.navbar-collapse
        ul.navbar-nav.mr-auto.mt-2.mt-md-0
          li.nav-item.active
            a.nav-link href="/admin/offers"
              | Offers
        ul.navbar-nav.my-2.my-lg-0
          li.nav-item
            a.nav-link href="#" = current_user.email
          li.nav-item
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"
    .container
      br
      = yield

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta name="robots" content="all,index,nofollow"
    title LemoneyChallenge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-inverse.bg-primary.navbar-toggleable-md
      button.navbar-toggler.navbar-toggler-right aria-controls="adminNavbar" aria-expanded="false" aria-label=("Toggle navigation") data-target="#adminNavbar" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      a.navbar-brand href='/' Challenge
      #adminNavbar.collapse.navbar-collapse
        ul.navbar-nav.mr-auto.mt-2.mt-md-0
        ul.navbar-nav.my-2.my-lg-0
          li.nav-item
            a.nav-link href="#" = current_user.email
          li.nav-item
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"
    .container
      br
      = yield

app/views/layouts/devise.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta name="robots" content="noindex,nofollow" /
    title LemoneyChallenge
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .container
      = yield